apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- helmrepositories/helmrepository-podinfo.yaml
- kustomizations/kustomization-podinfo.yaml
- namespaces/namespace-podinfo.yaml
